apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: ecommerce-apps        
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: 323398832779.dkr.ecr.me-south-1.amazonaws.com/cart-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: ecommerce-apps
spec:
  selector:
    app: cart-service
  ports:
    - port: 3003
      targetPort: 3003
