apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: ecommerce-apps      
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: 323398832779.dkr.ecr.me-south-1.amazonaws.com/catalog-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: ecommerce-apps
spec:
  selector:
    app: catalog-service
  ports:
    - port: 3002
      targetPort: 3002
