apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ecommerce-apps      
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: 323398832779.dkr.ecr.me-south-1.amazonaws.com/payment-service:latest
          ports:
            - containerPort: 3005
          env:
            - name: PORT
              value: "3005"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce-apps
spec:
  selector:
    app: payment-service
  ports:
    - port: 3005
      targetPort: 3005
