name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

jobs:
  delete-preview-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Set Image Tag
        run: echo "IMAGE_TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: 3MR-MLops/web-app-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops-folder
      
      - name: Remove Temporary Manifest

        run: |
          cd gitops-folder
          rm -f deployment-${{ env.IMAGE_TAG }}.yaml
          
          echo "done removing: deployment-${{ env.IMAGE_TAG }}.yaml"

      - name: Push Changes to GitOps Repo
        run: |
          cd gitops-folder
          
          git config user.name "GitHub Actions Bot"

          git config user.email "bot@github.com"
        
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Cleanup preview environment for ${{ env.IMAGE_TAG }}"
            git push
          else
            echo "No files to cleanup."
          fi